import { classNames } from "@ninjha01/nitro-ui";

const columns = [
  "Rank",
  "Target sequence",
  "Genomic location",
  "Strand",
  "GC content (%)",
  "Self-complementarity",
  "Efficiency",
] as const;

type TableColumn = typeof columns[number];

type TableData = {
  [key in TableColumn]: any;
};

const data: TableData[] = [
  {
    Rank: "1",
    "Target sequence": "CTTATATCACGTCCATAACGGGG",
    "Genomic location": "chr8:118110179",
    Strand: "-",
    "GC content (%)": "40",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "0",
    Efficiency: "70.92",
  },
  {
    Rank: "2",
    "Target sequence": "GGTAGTACGAACAATCCTCCAGG",
    "Genomic location": "chr8:117822515",
    Strand: "+",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "0",
    Efficiency: "59.17",
  },
  {
    Rank: "3",
    "Target sequence": "GAGAGCAAGGTAAGACTCGAAGG",
    "Genomic location": "chr8:117818421",
    Strand: "-",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "0",
    Efficiency: "55.29",
  },
  {
    Rank: "4",
    "Target sequence": "CGCAGAGCGTCCGGGAAGCGGGG",
    "Genomic location": "chr8:118110859",
    Strand: "+",
    "GC content (%)": "75",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "0",
    Efficiency: "47.58",
  },
  {
    Rank: "5",
    "Target sequence": "GCACAACGTCCTCCCCGTTATGG",
    "Genomic location": "chr8:118110167",
    Strand: "+",
    "GC content (%)": "60",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "0",
    Efficiency: "47.42",
  },
  {
    Rank: "6",
    "Target sequence": "ATATCACGTCCATAACGGGGAGG",
    "Genomic location": "chr8:118110176",
    Strand: "-",
    "GC content (%)": "50",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "1",
    Efficiency: "72.10",
  },
  {
    Rank: "7",
    "Target sequence": "AAAGCACCGTGTCCTCGTCAAGG",
    "Genomic location": "chr8:117812883",
    Strand: "+",
    "GC content (%)": "55",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "1",
    Efficiency: "60.40",
  },
  {
    Rank: "8",
    "Target sequence": "GATGTCAAACCCCACGTCCTCGG",
    "Genomic location": "chr8:118110414",
    Strand: "+",
    "GC content (%)": "55",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "1",
    Efficiency: "59.09",
  },
  {
    Rank: "9",
    "Target sequence": "CCCGTTATGGACGTGATATAAGG",
    "Genomic location": "chr8:118110180",
    Strand: "+",
    "GC content (%)": "45",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "1",
    Efficiency: "43.44",
  },
  {
    Rank: "10",
    "Target sequence": "TCTGCGCCCCTTCGTTCCTTGGG",
    "Genomic location": "chr8:118110842",
    Strand: "-",
    "GC content (%)": "60",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "1",
    Efficiency: "40.07",
  },
  {
    Rank: "11",
    "Target sequence": "TACAATCAGGTCTATTCATCAGG",
    "Genomic location": "chr8:117830319",
    Strand: "-",
    "GC content (%)": "35",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "1",
    Efficiency: "36.97",
  },
  {
    Rank: "12",
    "Target sequence": "CGATGGCCGCTAGAATGTTTTGG",
    "Genomic location": "chr8:118110632",
    Strand: "+",
    "GC content (%)": "50",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "1",
    Efficiency: "33.59",
  },
  {
    Rank: "13",
    "Target sequence": "TGAGGAATCCGGCTGAGTGGGGG",
    "Genomic location": "chr8:117799692",
    Strand: "-",
    "GC content (%)": "60",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "2",
    Efficiency: "60.94",
  },
  {
    Rank: "14",
    "Target sequence": "AACATTCTAGCGGCCATCGAGGG",
    "Genomic location": "chr8:118110628",
    Strand: "-",
    "GC content (%)": "50",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "2",
    Efficiency: "57.91",
  },
  {
    Rank: "15",
    "Target sequence": "CATCGCCTATGACGGCAGCTTGG",
    "Genomic location": "chr8:117835461",
    Strand: "+",
    "GC content (%)": "60",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "2",
    Efficiency: "50.91",
  },
  {
    Rank: "16",
    "Target sequence": "GCATGAATACGTTTGCCAGCTGG",
    "Genomic location": "chr8:117799820",
    Strand: "-",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "2",
    Efficiency: "47.75",
  },
  {
    Rank: "17",
    "Target sequence": "GTGCCTGTCGTCGTCATTGAAGG",
    "Genomic location": "chr8:117818445",
    Strand: "-",
    "GC content (%)": "55",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "2",
    Efficiency: "45.06",
  },
  {
    Rank: "18",
    "Target sequence": "TACGTATACCCACAGCAAAAAGG",
    "Genomic location": "chr8:118110676",
    Strand: "-",
    "GC content (%)": "40",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "2",
    Efficiency: "44.07",
  },
  {
    Rank: "19",
    "Target sequence": "GAAAACGGCTGCTCATAACCTGG",
    "Genomic location": "chr8:117812943",
    Strand: "+",
    "GC content (%)": "50",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "2",
    Efficiency: "44.56",
  },
  {
    Rank: "20",
    "Target sequence": "GACTTCTCGGGCTTCCCGTTGGG",
    "Genomic location": "chr8:117799876",
    Strand: "-",
    "GC content (%)": "60",
    "Self-complementarity": "3",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "2",
    Efficiency: "36.47",
  },
  {
    Rank: "21",
    "Target sequence": "CTTCGTTCCTTGGGATCAATTGG",
    "Genomic location": "chr8:118110833",
    Strand: "-",
    "GC content (%)": "45",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "2",
    Efficiency: "26.88",
  },
  {
    Rank: "22",
    "Target sequence": "ACCCCAGTCCGGATCATTTCTGG",
    "Genomic location": "chr8:118110882",
    Strand: "-",
    "GC content (%)": "55",
    "Self-complementarity": "4",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "2",
    Efficiency: "21.83",
  },
  {
    Rank: "23",
    "Target sequence": "GTGGACGAACGACTACTCCATGG",
    "Genomic location": "chr8:117807245",
    Strand: "-",
    "GC content (%)": "55",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "1",
    Efficiency: "63.81",
  },
  {
    Rank: "24",
    "Target sequence": "CCGGGGGGAAATGTGCACGCTGG",
    "Genomic location": "chr8:118110798",
    Strand: "+",
    "GC content (%)": "70",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "1",
    Efficiency: "56.16",
  },
  {
    Rank: "25",
    "Target sequence": "CACTTGGCCTGACTACACCGAGG",
    "Genomic location": "chr8:118110431",
    Strand: "-",
    "GC content (%)": "60",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "3",
    Efficiency: "76.36",
  },
  {
    Rank: "26",
    "Target sequence": "GCTTGCAGTTTAGGGCATCGAGG",
    "Genomic location": "chr8:118110951",
    Strand: "-",
    "GC content (%)": "55",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "3",
    Efficiency: "67.50",
  },
  {
    Rank: "27",
    "Target sequence": "GCCAGAAATGATCCGGACTGGGG",
    "Genomic location": "chr8:118110881",
    Strand: "+",
    "GC content (%)": "55",
    "Self-complementarity": "3",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "3",
    Efficiency: "69.36",
  },
  {
    Rank: "28",
    "Target sequence": "GCCAGTGTTGAAGCTTCTCGTGG",
    "Genomic location": "chr8:117819705",
    Strand: "-",
    "GC content (%)": "55",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "3",
    Efficiency: "63.17",
  },
  {
    Rank: "29",
    "Target sequence": "GTCCTCGTCAAGGCTGAGCACGG",
    "Genomic location": "chr8:117812893",
    Strand: "+",
    "GC content (%)": "60",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "3",
    Efficiency: "59.51",
  },
  {
    Rank: "30",
    "Target sequence": "GTAGAACCTGGAGCCCTCGATGG",
    "Genomic location": "chr8:118110615",
    Strand: "+",
    "GC content (%)": "60",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "3",
    Efficiency: "56.98",
  },
  {
    Rank: "31",
    "Target sequence": "GTCGCTGGGCAAAGTGGTCAGGG",
    "Genomic location": "chr8:117799849",
    Strand: "+",
    "GC content (%)": "60",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "3",
    Efficiency: "53.11",
  },
  {
    Rank: "32",
    "Target sequence": "TCTCCTTCAATGACGACGACAGG",
    "Genomic location": "chr8:117818442",
    Strand: "+",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "3",
    Efficiency: "52.88",
  },
  {
    Rank: "33",
    "Target sequence": "GACTACTCCATGGTGTTGACAGG",
    "Genomic location": "chr8:117807235",
    Strand: "-",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "3",
    Efficiency: "52.61",
  },
  {
    Rank: "34",
    "Target sequence": "TGGCATCTCGCTTCTGCCGGGGG",
    "Genomic location": "chr8:118110782",
    Strand: "+",
    "GC content (%)": "65",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "3",
    Efficiency: "52.35",
  },
  {
    Rank: "35",
    "Target sequence": "CGAGACATTGAGCGACTTTGAGG",
    "Genomic location": "chr8:117799710",
    Strand: "-",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "3",
    Efficiency: "50.63",
  },
  {
    Rank: "36",
    "Target sequence": "CGGCATGTAGCCAAACCAGCTGG",
    "Genomic location": "chr8:117799805",
    Strand: "+",
    "GC content (%)": "60",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "3",
    Efficiency: "50.57",
  },
  {
    Rank: "37",
    "Target sequence": "GCCTGACTACACCGAGGACGTGG",
    "Genomic location": "chr8:118110425",
    Strand: "-",
    "GC content (%)": "65",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "3",
    Efficiency: "47.00",
  },
  {
    Rank: "38",
    "Target sequence": "CAATCTCTCATCGCCTATGACGG",
    "Genomic location": "chr8:117835453",
    Strand: "+",
    "GC content (%)": "45",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "3",
    Efficiency: "48.00",
  },
  {
    Rank: "39",
    "Target sequence": "GTCTGGTTCCTCGTGGTCGCAGG",
    "Genomic location": "chr8:117837141",
    Strand: "-",
    "GC content (%)": "65",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "3",
    Efficiency: "40.16",
  },
  {
    Rank: "40",
    "Target sequence": "AATACGTTTGCCAGCTGGTTTGG",
    "Genomic location": "chr8:117799815",
    Strand: "-",
    "GC content (%)": "45",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "3",
    Efficiency: "35.32",
  },
  {
    Rank: "41",
    "Target sequence": "GGTCGAGCCTCATCTGAGAGTGG",
    "Genomic location": "chr8:117799777",
    Strand: "+",
    "GC content (%)": "60",
    "Self-complementarity": "3",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "2",
    Efficiency: "63.27",
  },
  {
    Rank: "42",
    "Target sequence": "GGATAACTCTAAGGAGCGGTGGG",
    "Genomic location": "chr8:117807281",
    Strand: "-",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "2",
    Efficiency: "50.49",
  },
  {
    Rank: "43",
    "Target sequence": "AAGCGGGGCCAGAAATGATCCGG",
    "Genomic location": "chr8:118110874",
    Strand: "+",
    "GC content (%)": "55",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "2",
    Efficiency: "48.02",
  },
  {
    Rank: "44",
    "Target sequence": "CCAGCGGTGTTTGGCTGGTAGGG",
    "Genomic location": "chr8:117818480",
    Strand: "+",
    "GC content (%)": "60",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "2",
    Efficiency: "33.20",
  },
  {
    Rank: "45",
    "Target sequence": "ACGGCTGCTCATAACCTGGGAGG",
    "Genomic location": "chr8:117812947",
    Strand: "+",
    "GC content (%)": "60",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "4",
    Efficiency: "70.45",
  },
  {
    Rank: "46",
    "Target sequence": "TTGGGATCAATTGGAAAACGAGG",
    "Genomic location": "chr8:118110824",
    Strand: "-",
    "GC content (%)": "40",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "4",
    Efficiency: "62.53",
  },
  {
    Rank: "47",
    "Target sequence": "CAATTGATCCCAAGGAACGAAGG",
    "Genomic location": "chr8:118110834",
    Strand: "+",
    "GC content (%)": "45",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "4",
    Efficiency: "61.24",
  },
  {
    Rank: "48",
    "Target sequence": "TGTCAACTTCCCGCTCACCTGGG",
    "Genomic location": "chr8:117819658",
    Strand: "+",
    "GC content (%)": "55",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "4",
    Efficiency: "59.30",
  },
  {
    Rank: "49",
    "Target sequence": "CGCCGTGCTCAGCCTTGACGAGG",
    "Genomic location": "chr8:117812895",
    Strand: "-",
    "GC content (%)": "70",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "4",
    Efficiency: "58.84",
  },
  {
    Rank: "50",
    "Target sequence": "GACCCAAGCCTGCGACCACGAGG",
    "Genomic location": "chr8:117837133",
    Strand: "+",
    "GC content (%)": "70",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "4",
    Efficiency: "60.08",
  },
  {
    Rank: "51",
    "Target sequence": "GGGATAACTCTAAGGAGCGGTGG",
    "Genomic location": "chr8:117807282",
    Strand: "-",
    "GC content (%)": "55",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "4",
    Efficiency: "56.81",
  },
  {
    Rank: "52",
    "Target sequence": "TTGGCATCTCGCTTCTGCCGGGG",
    "Genomic location": "chr8:118110781",
    Strand: "+",
    "GC content (%)": "60",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "4",
    Efficiency: "50.68",
  },
  {
    Rank: "53",
    "Target sequence": "TGACATCGGCCAGGCGATGCTGG",
    "Genomic location": "chr8:118110398",
    Strand: "-",
    "GC content (%)": "65",
    "Self-complementarity": "4",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "4",
    Efficiency: "47.30",
  },
  {
    Rank: "54",
    "Target sequence": "CGAGAAGCTTCAACACTGGCTGG",
    "Genomic location": "chr8:117819708",
    Strand: "+",
    "GC content (%)": "55",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "4",
    Efficiency: "42.38",
  },
  {
    Rank: "55",
    "Target sequence": "GGGCCAGAAATGATCCGGACTGG",
    "Genomic location": "chr8:118110879",
    Strand: "+",
    "GC content (%)": "60",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "4",
    Efficiency: "41.86",
  },
  {
    Rank: "56",
    "Target sequence": "GGCGCAGAGCGTCCGGGAAGCGG",
    "Genomic location": "chr8:118110857",
    Strand: "+",
    "GC content (%)": "75",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "4",
    Efficiency: "36.60",
  },
  {
    Rank: "57",
    "Target sequence": "CGATGAGAGATTGTTATTACAGG",
    "Genomic location": "chr8:117835443",
    Strand: "-",
    "GC content (%)": "35",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "4",
    Efficiency: "36.36",
  },
  {
    Rank: "58",
    "Target sequence": "GATAACTCTAAGGAGCGGTGGGG",
    "Genomic location": "chr8:117807280",
    Strand: "-",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "5",
    Efficiency: "74.42",
  },
  {
    Rank: "59",
    "Target sequence": "AATCGAAGCAGGACTCCATGCGG",
    "Genomic location": "chr8:118110731",
    Strand: "+",
    "GC content (%)": "50",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "5",
    Efficiency: "72.05",
  },
  {
    Rank: "60",
    "Target sequence": "GCTGCTATTTACCACAAGTGAGG",
    "Genomic location": "chr8:117807211",
    Strand: "-",
    "GC content (%)": "45",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "5",
    Efficiency: "68.99",
  },
  {
    Rank: "61",
    "Target sequence": "AGTACATGCTGGTATTCAAGGGG",
    "Genomic location": "chr8:118110243",
    Strand: "-",
    "GC content (%)": "40",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "5",
    Efficiency: "68.16",
  },
  {
    Rank: "62",
    "Target sequence": "GGTACCCCACAATCCTCTCAGGG",
    "Genomic location": "chr8:117807323",
    Strand: "+",
    "GC content (%)": "55",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "5",
    Efficiency: "63.62",
  },
  {
    Rank: "63",
    "Target sequence": "GGCATCTCGCTTCTGCCGGGGGG",
    "Genomic location": "chr8:118110783",
    Strand: "+",
    "GC content (%)": "70",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "5",
    Efficiency: "61.43",
  },
  {
    Rank: "64",
    "Target sequence": "TCGTTTTCCAATTGATCCCAAGG",
    "Genomic location": "chr8:118110826",
    Strand: "+",
    "GC content (%)": "40",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "5",
    Efficiency: "54.89",
  },
  {
    Rank: "65",
    "Target sequence": "CGCTGATCCACTCTCAGATGAGG",
    "Genomic location": "chr8:117799784",
    Strand: "-",
    "GC content (%)": "55",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "5",
    Efficiency: "55.71",
  },
  {
    Rank: "66",
    "Target sequence": "CTCAAAGTCGCTCAATGTCTCGG",
    "Genomic location": "chr8:117799711",
    Strand: "+",
    "GC content (%)": "45",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "5",
    Efficiency: "52.62",
  },
  {
    Rank: "67",
    "Target sequence": "TGTTGTCGTAGGGCAGAAAACGG",
    "Genomic location": "chr8:117812928",
    Strand: "+",
    "GC content (%)": "45",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "5",
    Efficiency: "51.17",
  },
  {
    Rank: "68",
    "Target sequence": "CAGCGGTGTTTGGCTGGTAGGGG",
    "Genomic location": "chr8:117818481",
    Strand: "+",
    "GC content (%)": "60",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "5",
    Efficiency: "49.24",
  },
  {
    Rank: "69",
    "Target sequence": "TGTCCTCACAATTGGCCAATTGG",
    "Genomic location": "chr8:117804814",
    Strand: "+",
    "GC content (%)": "45",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "5",
    Efficiency: "44.37",
  },
  {
    Rank: "70",
    "Target sequence": "TTAATTTATATTCCGGCACTTGG",
    "Genomic location": "chr8:118110447",
    Strand: "-",
    "GC content (%)": "30",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "5",
    Efficiency: "44.33",
  },
  {
    Rank: "71",
    "Target sequence": "GTGGTCAGGGTCAGCCCAACGGG",
    "Genomic location": "chr8:117799862",
    Strand: "+",
    "GC content (%)": "65",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "5",
    Efficiency: "43.76",
  },
  {
    Rank: "72",
    "Target sequence": "AGACTTCTCGGGCTTCCCGTTGG",
    "Genomic location": "chr8:117799877",
    Strand: "-",
    "GC content (%)": "60",
    "Self-complementarity": "3",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "5",
    Efficiency: "43.43",
  },
  {
    Rank: "73",
    "Target sequence": "GCCAGCGGTGTTTGGCTGGTAGG",
    "Genomic location": "chr8:117818479",
    Strand: "+",
    "GC content (%)": "65",
    "Self-complementarity": "3",
    MM0: "0",
    MM1: "1",
    MM2: "0",
    MM3: "3",
    Efficiency: "42.31",
  },
  {
    Rank: "74",
    "Target sequence": "CCCACGTCCTCGGTGTAGTCAGG",
    "Genomic location": "chr8:118110424",
    Strand: "+",
    "GC content (%)": "65",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "5",
    Efficiency: "36.29",
  },
  {
    Rank: "75",
    "Target sequence": "TATCACGTAACAGTTTAATATGG",
    "Genomic location": "chr8:117822547",
    Strand: "-",
    "GC content (%)": "25",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "5",
    Efficiency: "34.79",
  },
  {
    Rank: "76",
    "Target sequence": "AGTGGCAGGCCAGCGGTGTTTGG",
    "Genomic location": "chr8:117818471",
    Strand: "+",
    "GC content (%)": "65",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "2",
    Efficiency: "35.62",
  },
  {
    Rank: "77",
    "Target sequence": "ACGAAGGGGCGCAGAGCGTCCGG",
    "Genomic location": "chr8:118110850",
    Strand: "+",
    "GC content (%)": "70",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "5",
    Efficiency: "32.23",
  },
  {
    Rank: "78",
    "Target sequence": "GCGCAGAGCGTCCGGGAAGCGGG",
    "Genomic location": "chr8:118110858",
    Strand: "+",
    "GC content (%)": "75",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "5",
    Efficiency: "30.55",
  },
  {
    Rank: "79",
    "Target sequence": "CTCTGCGCCCCTTCGTTCCTTGG",
    "Genomic location": "chr8:118110843",
    Strand: "-",
    "GC content (%)": "65",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "5",
    Efficiency: "24.23",
  },
  {
    Rank: "80",
    "Target sequence": "TGGAACCAAGCTGCCGTCATAGG",
    "Genomic location": "chr8:117835466",
    Strand: "-",
    "GC content (%)": "55",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "4",
    Efficiency: "55.93",
  },
  {
    Rank: "81",
    "Target sequence": "CCTAAATTAGCATAGTAGTAAGG",
    "Genomic location": "chr8:117822464",
    Strand: "+",
    "GC content (%)": "30",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "4",
    Efficiency: "42.13",
  },
  {
    Rank: "82",
    "Target sequence": "GGACCAATTGGCCAATTGTGAGG",
    "Genomic location": "chr8:117804817",
    Strand: "-",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "6",
    Efficiency: "65.27",
  },
  {
    Rank: "83",
    "Target sequence": "AAACATTCTAGCGGCCATCGAGG",
    "Genomic location": "chr8:118110629",
    Strand: "-",
    "GC content (%)": "50",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "6",
    Efficiency: "62.01",
  },
  {
    Rank: "84",
    "Target sequence": "AATTGATCCCAAGGAACGAAGGG",
    "Genomic location": "chr8:118110835",
    Strand: "+",
    "GC content (%)": "40",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "6",
    Efficiency: "60.31",
  },
  {
    Rank: "85",
    "Target sequence": "AGAAATGATCCGGACTGGGGTGG",
    "Genomic location": "chr8:118110884",
    Strand: "+",
    "GC content (%)": "55",
    "Self-complementarity": "3",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "6",
    Efficiency: "60.02",
  },
  {
    Rank: "86",
    "Target sequence": "TGAAGGCGAAATCCACCTGCAGG",
    "Genomic location": "chr8:117807362",
    Strand: "+",
    "GC content (%)": "55",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "6",
    Efficiency: "55.22",
  },
  {
    Rank: "87",
    "Target sequence": "TCCTACCATTGTTCCACAAGTGG",
    "Genomic location": "chr8:118110482",
    Strand: "+",
    "GC content (%)": "45",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "6",
    Efficiency: "54.51",
  },
  {
    Rank: "88",
    "Target sequence": "GGGGTCCGAGGTGTAGAACCTGG",
    "Genomic location": "chr8:118110603",
    Strand: "+",
    "GC content (%)": "65",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "6",
    Efficiency: "52.00",
  },
  {
    Rank: "89",
    "Target sequence": "CGGGAAGCCCGAGAAGTCTAGGG",
    "Genomic location": "chr8:117799881",
    Strand: "+",
    "GC content (%)": "60",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "6",
    Efficiency: "51.36",
  },
  {
    Rank: "90",
    "Target sequence": "TTTGAGGAATCCGGCTGAGTGGG",
    "Genomic location": "chr8:117799694",
    Strand: "-",
    "GC content (%)": "50",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "6",
    Efficiency: "50.86",
  },
  {
    Rank: "91",
    "Target sequence": "GCCTTATATCACGTCCATAACGG",
    "Genomic location": "chr8:118110181",
    Strand: "-",
    "GC content (%)": "40",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "6",
    Efficiency: "46.24",
  },
  {
    Rank: "92",
    "Target sequence": "TCCCAGAAGTGGCTGCGCGCGGG",
    "Genomic location": "chr8:117807301",
    Strand: "+",
    "GC content (%)": "70",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "6",
    Efficiency: "44.71",
  },
  {
    Rank: "93",
    "Target sequence": "GACGTGATATAAGGCATTCCTGG",
    "Genomic location": "chr8:118110189",
    Strand: "+",
    "GC content (%)": "45",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "6",
    Efficiency: "43.55",
  },
  {
    Rank: "94",
    "Target sequence": "ACGTATACCCACAGCAAAAAGGG",
    "Genomic location": "chr8:118110675",
    Strand: "-",
    "GC content (%)": "40",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "6",
    Efficiency: "37.99",
  },
  {
    Rank: "95",
    "Target sequence": "CGCTCACCTGGGCACAGTACTGG",
    "Genomic location": "chr8:117819669",
    Strand: "+",
    "GC content (%)": "65",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "6",
    Efficiency: "34.37",
  },
  {
    Rank: "96",
    "Target sequence": "TGTCGCTGGGCAAAGTGGTCAGG",
    "Genomic location": "chr8:117799848",
    Strand: "+",
    "GC content (%)": "60",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "6",
    Efficiency: "32.69",
  },
  {
    Rank: "97",
    "Target sequence": "CTGTCAACTTCCCGCTCACCTGG",
    "Genomic location": "chr8:117819657",
    Strand: "+",
    "GC content (%)": "60",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "5",
    Efficiency: "31.03",
  },
  {
    Rank: "98",
    "Target sequence": "TCTGGGATAACTCTAAGGAGCGG",
    "Genomic location": "chr8:117807285",
    Strand: "-",
    "GC content (%)": "45",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "7",
    Efficiency: "70.50",
  },
  {
    Rank: "99",
    "Target sequence": "GACGACGACAGGCACAGCAGTGG",
    "Genomic location": "chr8:117818453",
    Strand: "+",
    "GC content (%)": "65",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "7",
    Efficiency: "65.25",
  },
  {
    Rank: "100",
    "Target sequence": "GATTGTATTAACTACACTAGAGG",
    "Genomic location": "chr8:117830229",
    Strand: "-",
    "GC content (%)": "30",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "7",
    Efficiency: "64.17",
  },
  {
    Rank: "101",
    "Target sequence": "AGAGCAAGGTAAGACTCGAAGGG",
    "Genomic location": "chr8:117818420",
    Strand: "-",
    "GC content (%)": "45",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "7",
    Efficiency: "61.50",
  },
  {
    Rank: "102",
    "Target sequence": "AAAACGGCTGCTCATAACCTGGG",
    "Genomic location": "chr8:117812944",
    Strand: "+",
    "GC content (%)": "45",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "7",
    Efficiency: "61.46",
  },
  {
    Rank: "103",
    "Target sequence": "TCCACTTGTGGAACAATGGTAGG",
    "Genomic location": "chr8:118110483",
    Strand: "-",
    "GC content (%)": "45",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "7",
    Efficiency: "58.40",
  },
  {
    Rank: "104",
    "Target sequence": "TGTGATGCTCAGCAATGGATGGG",
    "Genomic location": "chr8:117835515",
    Strand: "-",
    "GC content (%)": "45",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "7",
    Efficiency: "57.18",
  },
  {
    Rank: "105",
    "Target sequence": "CCATAGAACTATGATCTGAAAGG",
    "Genomic location": "chr8:117818516",
    Strand: "+",
    "GC content (%)": "35",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "7",
    Efficiency: "50.77",
  },
  {
    Rank: "106",
    "Target sequence": "TCTAAGGATCATCCCAGGACAGG",
    "Genomic location": "chr8:118110313",
    Strand: "-",
    "GC content (%)": "50",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "7",
    Efficiency: "48.53",
  },
  {
    Rank: "107",
    "Target sequence": "TATTCATGCAGCTCTGTCGCTGG",
    "Genomic location": "chr8:117799834",
    Strand: "+",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "7",
    Efficiency: "42.67",
  },
  {
    Rank: "108",
    "Target sequence": "ACGGGAAGCCCGAGAAGTCTAGG",
    "Genomic location": "chr8:117799880",
    Strand: "+",
    "GC content (%)": "60",
    "Self-complementarity": "3",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "7",
    Efficiency: "43.26",
  },
  {
    Rank: "109",
    "Target sequence": "AGTTGGCATCTCGCTTCTGCCGG",
    "Genomic location": "chr8:118110779",
    Strand: "+",
    "GC content (%)": "55",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "7",
    Efficiency: "38.52",
  },
  {
    Rank: "110",
    "Target sequence": "TCTTTCTAGGTATGATTATCGGG",
    "Genomic location": "chr8:117837188",
    Strand: "-",
    "GC content (%)": "30",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "7",
    Efficiency: "33.54",
  },
  {
    Rank: "111",
    "Target sequence": "GGTGGGGATACACATCAAAGTGG",
    "Genomic location": "chr8:117807264",
    Strand: "-",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "6",
    Efficiency: "73.51",
  },
  {
    Rank: "112",
    "Target sequence": "GGGTACCCCACAATCCTCTCAGG",
    "Genomic location": "chr8:117807322",
    Strand: "+",
    "GC content (%)": "60",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "6",
    Efficiency: "42.07",
  },
  {
    Rank: "113",
    "Target sequence": "TTCCTCGTGGTCGCAGGCTTGGG",
    "Genomic location": "chr8:117837135",
    Strand: "-",
    "GC content (%)": "60",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "6",
    Efficiency: "39.81",
  },
  {
    Rank: "114",
    "Target sequence": "ACCCCGCGCGCAGCCACTTCTGG",
    "Genomic location": "chr8:117807303",
    Strand: "-",
    "GC content (%)": "75",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "6",
    Efficiency: "16.79",
  },
  {
    Rank: "115",
    "Target sequence": "CTCATCTGAGAGTGGATCAGCGG",
    "Genomic location": "chr8:117799785",
    Strand: "+",
    "GC content (%)": "50",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "8",
    Efficiency: "63.37",
  },
  {
    Rank: "116",
    "Target sequence": "GGTGTAGTCAGGCCAAGTGCCGG",
    "Genomic location": "chr8:118110435",
    Strand: "+",
    "GC content (%)": "60",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "5",
    Efficiency: "60.95",
  },
  {
    Rank: "117",
    "Target sequence": "CGTATACCCACAGCAAAAAGGGG",
    "Genomic location": "chr8:118110674",
    Strand: "-",
    "GC content (%)": "45",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "8",
    Efficiency: "57.62",
  },
  {
    Rank: "118",
    "Target sequence": "GCCCGAGAAGTCTAGGGAGAAGG",
    "Genomic location": "chr8:117799887",
    Strand: "+",
    "GC content (%)": "60",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "8",
    Efficiency: "54.62",
  },
  {
    Rank: "119",
    "Target sequence": "AAGTACATGCTGGTATTCAAGGG",
    "Genomic location": "chr8:118110244",
    Strand: "-",
    "GC content (%)": "35",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "8",
    Efficiency: "53.05",
  },
  {
    Rank: "120",
    "Target sequence": "TGAAGCCGTTTTTCTTGCAAAGG",
    "Genomic location": "chr8:118110704",
    Strand: "+",
    "GC content (%)": "40",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "8",
    Efficiency: "52.95",
  },
  {
    Rank: "121",
    "Target sequence": "TTTACCACAAGTGAGGAATCTGG",
    "Genomic location": "chr8:117807204",
    Strand: "-",
    "GC content (%)": "40",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "8",
    Efficiency: "51.34",
  },
  {
    Rank: "122",
    "Target sequence": "CCCAGAAGTGGCTGCGCGCGGGG",
    "Genomic location": "chr8:117807302",
    Strand: "+",
    "GC content (%)": "75",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "8",
    Efficiency: "49.48",
  },
  {
    Rank: "123",
    "Target sequence": "TACCGCTGTGTTCTTCTCTCCGG",
    "Genomic location": "chr8:118110920",
    Strand: "+",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "8",
    Efficiency: "49.06",
  },
  {
    Rank: "124",
    "Target sequence": "GTTGGCATCTCGCTTCTGCCGGG",
    "Genomic location": "chr8:118110780",
    Strand: "+",
    "GC content (%)": "60",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "7",
    Efficiency: "41.69",
  },
  {
    Rank: "125",
    "Target sequence": "ACCACAGTATTCATCTTATCTGG",
    "Genomic location": "chr8:117822495",
    Strand: "-",
    "GC content (%)": "35",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "7",
    Efficiency: "24.93",
  },
  {
    Rank: "126",
    "Target sequence": "TAGAAGGAATCTGTAACACAAGG",
    "Genomic location": "chr8:117830340",
    Strand: "+",
    "GC content (%)": "35",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "9",
    Efficiency: "68.98",
  },
  {
    Rank: "127",
    "Target sequence": "CCCAGATAAGATGAATACTGTGG",
    "Genomic location": "chr8:117822494",
    Strand: "+",
    "GC content (%)": "40",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "9",
    Efficiency: "62.40",
  },
  {
    Rank: "128",
    "Target sequence": "ATTCATGCAGCTCTGTCGCTGGG",
    "Genomic location": "chr8:117799835",
    Strand: "+",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "9",
    Efficiency: "57.26",
  },
  {
    Rank: "129",
    "Target sequence": "GCACATACTGAGGTGACAACTGG",
    "Genomic location": "chr8:118110533",
    Strand: "+",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "9",
    Efficiency: "52.39",
  },
  {
    Rank: "130",
    "Target sequence": "AGACCAGGGGGGTCACCGCATGG",
    "Genomic location": "chr8:117819738",
    Strand: "+",
    "GC content (%)": "70",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "9",
    Efficiency: "48.64",
  },
  {
    Rank: "131",
    "Target sequence": "CGAAGTCCCCTTTTTTGCTCAGG",
    "Genomic location": "chr8:117835551",
    Strand: "-",
    "GC content (%)": "50",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "9",
    Efficiency: "37.93",
  },
  {
    Rank: "132",
    "Target sequence": "TTTCGGAGGCTTGCAGTTTAGGG",
    "Genomic location": "chr8:118110959",
    Strand: "-",
    "GC content (%)": "45",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "9",
    Efficiency: "33.47",
  },
  {
    Rank: "133",
    "Target sequence": "CCAGTCTTTGCCATGCTTGCAGG",
    "Genomic location": "chr8:118110135",
    Strand: "+",
    "GC content (%)": "55",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "9",
    Efficiency: "24.66",
  },
  {
    Rank: "134",
    "Target sequence": "CAGGATGAAATAGCGTTTTTTGG",
    "Genomic location": "chr8:118111017",
    Strand: "+",
    "GC content (%)": "35",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "9",
    Efficiency: "25.06",
  },
  {
    Rank: "135",
    "Target sequence": "GCTTGGGTCCTTCAGATTCCTGG",
    "Genomic location": "chr8:117837119",
    Strand: "-",
    "GC content (%)": "55",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "9",
    Efficiency: "25.03",
  },
  {
    Rank: "136",
    "Target sequence": "ACTTTCTGTCTGGTTCCTCGTGG",
    "Genomic location": "chr8:117837148",
    Strand: "-",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "8",
    Efficiency: "62.32",
  },
  {
    Rank: "137",
    "Target sequence": "TAGAGGTAAGTGAGACCACTTGG",
    "Genomic location": "chr8:117830212",
    Strand: "-",
    "GC content (%)": "45",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "8",
    Efficiency: "56.35",
  },
  {
    Rank: "138",
    "Target sequence": "ACAGCAGACACAATTCTTGTGGG",
    "Genomic location": "chr8:117830277",
    Strand: "-",
    "GC content (%)": "40",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "8",
    Efficiency: "53.21",
  },
  {
    Rank: "139",
    "Target sequence": "CACGGTGCTTTCAACAACAGAGG",
    "Genomic location": "chr8:117812871",
    Strand: "-",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "10",
    Efficiency: "69.88",
  },
  {
    Rank: "140",
    "Target sequence": "TCTGTGATGATGTTGTCGTAGGG",
    "Genomic location": "chr8:117812918",
    Strand: "+",
    "GC content (%)": "40",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "10",
    Efficiency: "66.21",
  },
  {
    Rank: "141",
    "Target sequence": "GAGCAAGGTAAGACTCGAAGGGG",
    "Genomic location": "chr8:117818419",
    Strand: "-",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "10",
    Efficiency: "59.59",
  },
  {
    Rank: "142",
    "Target sequence": "ACTATGATCTGAAAGGGATGGGG",
    "Genomic location": "chr8:117818523",
    Strand: "+",
    "GC content (%)": "40",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "10",
    Efficiency: "58.77",
  },
  {
    Rank: "143",
    "Target sequence": "ACCTGGTCTTTAAAGAGGACGGG",
    "Genomic location": "chr8:117799755",
    Strand: "+",
    "GC content (%)": "45",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "10",
    Efficiency: "50.82",
  },
  {
    Rank: "144",
    "Target sequence": "GCACAATGCCACTTTCTGTCTGG",
    "Genomic location": "chr8:117837158",
    Strand: "-",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "10",
    Efficiency: "39.70",
  },
  {
    Rank: "145",
    "Target sequence": "GCCACGAGAAGCTTCAACACTGG",
    "Genomic location": "chr8:117819704",
    Strand: "+",
    "GC content (%)": "55",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "9",
    Efficiency: "60.01",
  },
  {
    Rank: "146",
    "Target sequence": "CCTGGTCTTTAAAGAGGACGGGG",
    "Genomic location": "chr8:117799756",
    Strand: "+",
    "GC content (%)": "50",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "9",
    Efficiency: "60.05",
  },
  {
    Rank: "147",
    "Target sequence": "GCAAAGGGTGAAATCGAAGCAGG",
    "Genomic location": "chr8:118110720",
    Strand: "+",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "9",
    Efficiency: "58.39",
  },
  {
    Rank: "148",
    "Target sequence": "CGTGGGGTTTGACATCGGCCAGG",
    "Genomic location": "chr8:118110407",
    Strand: "-",
    "GC content (%)": "65",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "9",
    Efficiency: "57.23",
  },
  {
    Rank: "149",
    "Target sequence": "TGGCTTGCACCACCCCAGTCCGG",
    "Genomic location": "chr8:118110893",
    Strand: "-",
    "GC content (%)": "65",
    "Self-complementarity": "3",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "9",
    Efficiency: "51.62",
  },
  {
    Rank: "150",
    "Target sequence": "CTTTGAGGAATCCGGCTGAGTGG",
    "Genomic location": "chr8:117799695",
    Strand: "-",
    "GC content (%)": "55",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "11",
    Efficiency: "59.52",
  },
  {
    Rank: "151",
    "Target sequence": "TCCTCTCAGGAAGTACATGCTGG",
    "Genomic location": "chr8:118110254",
    Strand: "-",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "11",
    Efficiency: "55.26",
  },
  {
    Rank: "152",
    "Target sequence": "TCTTTTCTAAGGATCATCCCAGG",
    "Genomic location": "chr8:118110318",
    Strand: "-",
    "GC content (%)": "40",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "11",
    Efficiency: "52.83",
  },
  {
    Rank: "153",
    "Target sequence": "TACAGATTCCTTCTACAATCAGG",
    "Genomic location": "chr8:117830332",
    Strand: "-",
    "GC content (%)": "35",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "11",
    Efficiency: "44.46",
  },
  {
    Rank: "154",
    "Target sequence": "AGCTTCCCTGAGAGGATTGTGGG",
    "Genomic location": "chr8:117807328",
    Strand: "-",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "11",
    Efficiency: "43.72",
  },
  {
    Rank: "155",
    "Target sequence": "GGCCAGAAATGATCCGGACTGGG",
    "Genomic location": "chr8:118110880",
    Strand: "+",
    "GC content (%)": "55",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "11",
    Efficiency: "42.31",
  },
  {
    Rank: "156",
    "Target sequence": "GAAGTACATGCTGGTATTCAAGG",
    "Genomic location": "chr8:118110245",
    Strand: "-",
    "GC content (%)": "40",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "11",
    Efficiency: "37.53",
  },
  {
    Rank: "157",
    "Target sequence": "ATTCACTGCAGTCATCCATGCGG",
    "Genomic location": "chr8:117819753",
    Strand: "-",
    "GC content (%)": "45",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "10",
    Efficiency: "75.10",
  },
  {
    Rank: "158",
    "Target sequence": "GCATGTACTTCCTGAGAGGAGGG",
    "Genomic location": "chr8:118110257",
    Strand: "+",
    "GC content (%)": "50",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "10",
    Efficiency: "64.02",
  },
  {
    Rank: "159",
    "Target sequence": "CAAAGGCAAGAAGTGCCGCATGG",
    "Genomic location": "chr8:118110746",
    Strand: "-",
    "GC content (%)": "55",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "10",
    Efficiency: "60.45",
  },
  {
    Rank: "160",
    "Target sequence": "TTGAGCGACTTTGAGGAATCCGG",
    "Genomic location": "chr8:117799703",
    Strand: "-",
    "GC content (%)": "45",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "10",
    Efficiency: "50.16",
  },
  {
    Rank: "161",
    "Target sequence": "CGAAGGGGCGCAGAGCGTCCGGG",
    "Genomic location": "chr8:118110851",
    Strand: "+",
    "GC content (%)": "75",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "10",
    Efficiency: "48.89",
  },
  {
    Rank: "162",
    "Target sequence": "ATTGATCCCAAGGAACGAAGGGG",
    "Genomic location": "chr8:118110836",
    Strand: "+",
    "GC content (%)": "45",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "9",
    Efficiency: "69.31",
  },
  {
    Rank: "163",
    "Target sequence": "GGATCATCCCAGGACAGGAGGGG",
    "Genomic location": "chr8:118110308",
    Strand: "-",
    "GC content (%)": "60",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "12",
    Efficiency: "64.22",
  },
  {
    Rank: "164",
    "Target sequence": "ATCCATTGCTGAGCATCACAGGG",
    "Genomic location": "chr8:117835518",
    Strand: "+",
    "GC content (%)": "45",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "12",
    Efficiency: "64.78",
  },
  {
    Rank: "165",
    "Target sequence": "CGTCATTGAAGGAGAGAGCAAGG",
    "Genomic location": "chr8:117818434",
    Strand: "-",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "12",
    Efficiency: "60.10",
  },
  {
    Rank: "166",
    "Target sequence": "GAAGCCGTTTTTCTTGCAAAGGG",
    "Genomic location": "chr8:118110705",
    Strand: "+",
    "GC content (%)": "40",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "12",
    Efficiency: "58.59",
  },
  {
    Rank: "167",
    "Target sequence": "TTGAGGAATCCGGCTGAGTGGGG",
    "Genomic location": "chr8:117799693",
    Strand: "-",
    "GC content (%)": "55",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "12",
    Efficiency: "57.55",
  },
  {
    Rank: "168",
    "Target sequence": "GCCCTTTTGTTTTATTTCGGAGG",
    "Genomic location": "chr8:118110973",
    Strand: "-",
    "GC content (%)": "40",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "9",
    Efficiency: "49.28",
  },
  {
    Rank: "169",
    "Target sequence": "ACAAAGAGGCACGCCTGGCTGGG",
    "Genomic location": "chr8:118110583",
    Strand: "+",
    "GC content (%)": "60",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "12",
    Efficiency: "47.34",
  },
  {
    Rank: "170",
    "Target sequence": "TCATTTCTGGCCCCGCTTCCCGG",
    "Genomic location": "chr8:118110869",
    Strand: "-",
    "GC content (%)": "60",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "12",
    Efficiency: "32.57",
  },
  {
    Rank: "171",
    "Target sequence": "GAAGCTCTGCCACACTGTGAAGG",
    "Genomic location": "chr8:117807345",
    Strand: "+",
    "GC content (%)": "55",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "11",
    Efficiency: "60.28",
  },
  {
    Rank: "172",
    "Target sequence": "GACCCAGAAGAAGCAGTATAAGG",
    "Genomic location": "chr8:117804739",
    Strand: "-",
    "GC content (%)": "45",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "11",
    Efficiency: "40.39",
  },
  {
    Rank: "173",
    "Target sequence": "CATGAGAATGTCCTCACAATTGG",
    "Genomic location": "chr8:117804806",
    Strand: "+",
    "GC content (%)": "40",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "11",
    Efficiency: "41.13",
  },
  {
    Rank: "174",
    "Target sequence": "GACAAAGAGGCACGCCTGGCTGG",
    "Genomic location": "chr8:118110582",
    Strand: "+",
    "GC content (%)": "65",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "11",
    Efficiency: "32.68",
  },
  {
    Rank: "175",
    "Target sequence": "ATATGGAACAAACATCCTGGAGG",
    "Genomic location": "chr8:117822530",
    Strand: "-",
    "GC content (%)": "40",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "13",
    Efficiency: "68.49",
  },
  {
    Rank: "176",
    "Target sequence": "CTGACTACACCGAGGACGTGGGG",
    "Genomic location": "chr8:118110423",
    Strand: "-",
    "GC content (%)": "60",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "13",
    Efficiency: "60.34",
  },
  {
    Rank: "177",
    "Target sequence": "AAGTGCAGAGTCTCCACTTGTGG",
    "Genomic location": "chr8:118110495",
    Strand: "-",
    "GC content (%)": "50",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "13",
    Efficiency: "58.14",
  },
  {
    Rank: "178",
    "Target sequence": "AAGGGGAAGAGGTACCTGACAGG",
    "Genomic location": "chr8:118110226",
    Strand: "-",
    "GC content (%)": "55",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "13",
    Efficiency: "56.25",
  },
  {
    Rank: "179",
    "Target sequence": "TGAATAGACCTGATTGTAGAAGG",
    "Genomic location": "chr8:117830324",
    Strand: "+",
    "GC content (%)": "35",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "13",
    Efficiency: "52.82",
  },
  {
    Rank: "180",
    "Target sequence": "TAGCGGCCATCGAGGGCTCCAGG",
    "Genomic location": "chr8:118110621",
    Strand: "-",
    "GC content (%)": "70",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "13",
    Efficiency: "44.49",
  },
  {
    Rank: "181",
    "Target sequence": "AGAGATTGTTATTACAGGTAAGG",
    "Genomic location": "chr8:117835438",
    Strand: "-",
    "GC content (%)": "30",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "10",
    Efficiency: "42.46",
  },
  {
    Rank: "182",
    "Target sequence": "TCAGGACAAAGAGGCACGCCTGG",
    "Genomic location": "chr8:118110578",
    Strand: "+",
    "GC content (%)": "60",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "12",
    Efficiency: "50.03",
  },
  {
    Rank: "183",
    "Target sequence": "TGTCTGATCCTATCCCTGTCAGG",
    "Genomic location": "chr8:118110212",
    Strand: "+",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "12",
    Efficiency: "48.90",
  },
  {
    Rank: "184",
    "Target sequence": "GCAGGCCAGCGGTGTTTGGCTGG",
    "Genomic location": "chr8:117818475",
    Strand: "+",
    "GC content (%)": "70",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "12",
    Efficiency: "44.55",
  },
  {
    Rank: "185",
    "Target sequence": "TTCAGTACTGATGCTGGCTTTGG",
    "Genomic location": "chr8:118110375",
    Strand: "+",
    "GC content (%)": "45",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "1",
    MM2: "1",
    MM3: "10",
    Efficiency: "32.53",
  },
  {
    Rank: "186",
    "Target sequence": "ATTGGTCCACCATGTTCTTCAGG",
    "Genomic location": "chr8:117804832",
    Strand: "+",
    "GC content (%)": "45",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "3",
    MM3: "9",
    Efficiency: "29.30",
  },
  {
    Rank: "187",
    "Target sequence": "GCTTCCCTGAGAGGATTGTGGGG",
    "Genomic location": "chr8:117807327",
    Strand: "-",
    "GC content (%)": "55",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "14",
    Efficiency: "71.80",
  },
  {
    Rank: "188",
    "Target sequence": "CAGTATAAGGAGACAATGATGGG",
    "Genomic location": "chr8:117804726",
    Strand: "-",
    "GC content (%)": "35",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "14",
    Efficiency: "63.71",
  },
  {
    Rank: "189",
    "Target sequence": "AGCATGTACTTCCTGAGAGGAGG",
    "Genomic location": "chr8:118110256",
    Strand: "+",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "11",
    Efficiency: "61.84",
  },
  {
    Rank: "190",
    "Target sequence": "GACCTGGTCTTTAAAGAGGACGG",
    "Genomic location": "chr8:117799754",
    Strand: "+",
    "GC content (%)": "45",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "14",
    Efficiency: "59.36",
  },
  {
    Rank: "191",
    "Target sequence": "GAGCTTCCCTGAGAGGATTGTGG",
    "Genomic location": "chr8:117807329",
    Strand: "-",
    "GC content (%)": "55",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "14",
    Efficiency: "53.23",
  },
  {
    Rank: "192",
    "Target sequence": "TGTGTTCTTCTCTCCGGCTGTGG",
    "Genomic location": "chr8:118110926",
    Strand: "+",
    "GC content (%)": "55",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "14",
    Efficiency: "51.45",
  },
  {
    Rank: "193",
    "Target sequence": "GCCTTTGTAGATGCTGGAGTTGG",
    "Genomic location": "chr8:118110762",
    Strand: "+",
    "GC content (%)": "50",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "14",
    Efficiency: "43.85",
  },
  {
    Rank: "194",
    "Target sequence": "TTCTGGGTCACTTTGATTGGAGG",
    "Genomic location": "chr8:117804753",
    Strand: "+",
    "GC content (%)": "45",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "14",
    Efficiency: "32.92",
  },
  {
    Rank: "195",
    "Target sequence": "ATGTCCAGATTCCTCACTTGTGG",
    "Genomic location": "chr8:117807200",
    Strand: "+",
    "GC content (%)": "45",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "3",
    MM3: "10",
    Efficiency: "59.90",
  },
  {
    Rank: "196",
    "Target sequence": "GTCTTTGCCATGCTTGCAGGTGG",
    "Genomic location": "chr8:118110138",
    Strand: "+",
    "GC content (%)": "55",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "13",
    Efficiency: "55.59",
  },
  {
    Rank: "197",
    "Target sequence": "CTGTGATGCTCAGCAATGGATGG",
    "Genomic location": "chr8:117835516",
    Strand: "-",
    "GC content (%)": "50",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "3",
    MM3: "10",
    Efficiency: "52.25",
  },
  {
    Rank: "198",
    "Target sequence": "CATCCATTGCTGAGCATCACAGG",
    "Genomic location": "chr8:117835517",
    Strand: "+",
    "GC content (%)": "50",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "13",
    Efficiency: "42.57",
  },
  {
    Rank: "199",
    "Target sequence": "ATGGATGACTGCAGTGAATTTGG",
    "Genomic location": "chr8:117819757",
    Strand: "+",
    "GC content (%)": "40",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "13",
    Efficiency: "38.55",
  },
  {
    Rank: "200",
    "Target sequence": "ACCAGCATGTACTTCCTGAGAGG",
    "Genomic location": "chr8:118110253",
    Strand: "+",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "15",
    Efficiency: "70.73",
  },
  {
    Rank: "201",
    "Target sequence": "GAGGACGTGGGGTTTGACATCGG",
    "Genomic location": "chr8:118110412",
    Strand: "-",
    "GC content (%)": "55",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "15",
    Efficiency: "66.63",
  },
  {
    Rank: "202",
    "Target sequence": "GCAGACACAATTCTTGTGGGAGG",
    "Genomic location": "chr8:117830274",
    Strand: "-",
    "GC content (%)": "50",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "15",
    Efficiency: "64.62",
  },
  {
    Rank: "203",
    "Target sequence": "CTCAAATTGTGCACATACTGAGG",
    "Genomic location": "chr8:118110523",
    Strand: "+",
    "GC content (%)": "40",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "12",
    Efficiency: "54.00",
  },
  {
    Rank: "204",
    "Target sequence": "GCTCACCTGGGCACAGTACTGGG",
    "Genomic location": "chr8:117819670",
    Strand: "+",
    "GC content (%)": "60",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "12",
    Efficiency: "47.29",
  },
  {
    Rank: "205",
    "Target sequence": "GAAGAACATGGTGGACCAATTGG",
    "Genomic location": "chr8:117804829",
    Strand: "-",
    "GC content (%)": "45",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "15",
    Efficiency: "46.11",
  },
  {
    Rank: "206",
    "Target sequence": "AACTATGATCTGAAAGGGATGGG",
    "Genomic location": "chr8:117818522",
    Strand: "+",
    "GC content (%)": "35",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "15",
    Efficiency: "44.77",
  },
  {
    Rank: "207",
    "Target sequence": "CATTCTCTGAAGTGATTAATTGG",
    "Genomic location": "chr8:117835486",
    Strand: "-",
    "GC content (%)": "30",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "15",
    Efficiency: "21.90",
  },
  {
    Rank: "208",
    "Target sequence": "TGGGTCCTTCAGATTCCTGGAGG",
    "Genomic location": "chr8:117837116",
    Strand: "-",
    "GC content (%)": "55",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "14",
    Efficiency: "58.97",
  },
  {
    Rank: "209",
    "Target sequence": "AGACACTTACTTCTCATACTCGG",
    "Genomic location": "chr8:118110075",
    Strand: "+",
    "GC content (%)": "35",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "14",
    Efficiency: "58.34",
  },
  {
    Rank: "210",
    "Target sequence": "GACAGCAGACACAATTCTTGTGG",
    "Genomic location": "chr8:117830278",
    Strand: "-",
    "GC content (%)": "45",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "14",
    Efficiency: "54.12",
  },
  {
    Rank: "211",
    "Target sequence": "CATAGAACTATGATCTGAAAGGG",
    "Genomic location": "chr8:117818517",
    Strand: "+",
    "GC content (%)": "30",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "14",
    Efficiency: "49.27",
  },
  {
    Rank: "212",
    "Target sequence": "GGGCTCCAGGTTCTACACCTCGG",
    "Genomic location": "chr8:118110608",
    Strand: "-",
    "GC content (%)": "60",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "16",
    Efficiency: "70.48",
  },
  {
    Rank: "213",
    "Target sequence": "GGATGATCCTTAGAAAAGAGGGG",
    "Genomic location": "chr8:118110322",
    Strand: "+",
    "GC content (%)": "40",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "13",
    Efficiency: "67.02",
  },
  {
    Rank: "214",
    "Target sequence": "AGCTCTGTCGCTGGGCAAAGTGG",
    "Genomic location": "chr8:117799843",
    Strand: "+",
    "GC content (%)": "60",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "13",
    Efficiency: "62.50",
  },
  {
    Rank: "215",
    "Target sequence": "GAGAAGCTTCAACACTGGCTGGG",
    "Genomic location": "chr8:117819709",
    Strand: "+",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "13",
    Efficiency: "59.82",
  },
  {
    Rank: "216",
    "Target sequence": "GAAGAACACAGCGGTAGGAATGG",
    "Genomic location": "chr8:118110913",
    Strand: "-",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "16",
    Efficiency: "54.11",
  },
  {
    Rank: "217",
    "Target sequence": "AGTCTCCACTTGTGGAACAATGG",
    "Genomic location": "chr8:118110487",
    Strand: "-",
    "GC content (%)": "45",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "16",
    Efficiency: "54.97",
  },
  {
    Rank: "218",
    "Target sequence": "GAAGTTTTCAGTACTGATGCTGG",
    "Genomic location": "chr8:118110369",
    Strand: "+",
    "GC content (%)": "40",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "13",
    Efficiency: "52.98",
  },
  {
    Rank: "219",
    "Target sequence": "GGAATCCGGCTGAGTGGGGGAGG",
    "Genomic location": "chr8:117799689",
    Strand: "-",
    "GC content (%)": "70",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "16",
    Efficiency: "40.64",
  },
  {
    Rank: "220",
    "Target sequence": "ATTTCGGAGGCTTGCAGTTTAGG",
    "Genomic location": "chr8:118110960",
    Strand: "-",
    "GC content (%)": "45",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "13",
    Efficiency: "20.80",
  },
  {
    Rank: "221",
    "Target sequence": "TGGATTTCGCCTTCACAGTGTGG",
    "Genomic location": "chr8:117807354",
    Strand: "-",
    "GC content (%)": "50",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "15",
    Efficiency: "63.77",
  },
  {
    Rank: "222",
    "Target sequence": "GATGACTGCAGTGAATTTGGAGG",
    "Genomic location": "chr8:117819760",
    Strand: "+",
    "GC content (%)": "45",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "15",
    Efficiency: "60.05",
  },
  {
    Rank: "223",
    "Target sequence": "TATTTCATCCTGCTCTCAGCTGG",
    "Genomic location": "chr8:118111006",
    Strand: "-",
    "GC content (%)": "45",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "3",
    MM3: "12",
    Efficiency: "48.56",
  },
  {
    Rank: "224",
    "Target sequence": "AGGTAAGTGAATTTCCTCCAGGG",
    "Genomic location": "chr8:117822444",
    Strand: "-",
    "GC content (%)": "40",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "17",
    Efficiency: "58.11",
  },
  {
    Rank: "225",
    "Target sequence": "TAAGGAGACAATGATGGGACAGG",
    "Genomic location": "chr8:117804721",
    Strand: "-",
    "GC content (%)": "45",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "17",
    Efficiency: "52.62",
  },
  {
    Rank: "226",
    "Target sequence": "GAACTATGATCTGAAAGGGATGG",
    "Genomic location": "chr8:117818521",
    Strand: "+",
    "GC content (%)": "40",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "17",
    Efficiency: "50.58",
  },
  {
    Rank: "227",
    "Target sequence": "CATCCATGCGGTGACCCCCCTGG",
    "Genomic location": "chr8:117819741",
    Strand: "-",
    "GC content (%)": "70",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "14",
    Efficiency: "47.20",
  },
  {
    Rank: "228",
    "Target sequence": "GAGTATGAGAAGTAAGTGTCTGG",
    "Genomic location": "chr8:118110073",
    Strand: "-",
    "GC content (%)": "40",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "17",
    Efficiency: "43.53",
  },
  {
    Rank: "229",
    "Target sequence": "TGAGAAGTAAGTGTCTGGGCTGG",
    "Genomic location": "chr8:118110068",
    Strand: "-",
    "GC content (%)": "50",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "16",
    Efficiency: "58.74",
  },
  {
    Rank: "230",
    "Target sequence": "AAGACCAGGTCTCTATTTTGAGG",
    "Genomic location": "chr8:117799742",
    Strand: "-",
    "GC content (%)": "40",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "16",
    Efficiency: "36.71",
  },
  {
    Rank: "231",
    "Target sequence": "GAGGTAAGAACCCATGCCTGAGG",
    "Genomic location": "chr8:117812852",
    Strand: "-",
    "GC content (%)": "55",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "18",
    Efficiency: "68.33",
  },
  {
    Rank: "232",
    "Target sequence": "ATGACTGCAGTGAATTTGGAGGG",
    "Genomic location": "chr8:117819761",
    Strand: "+",
    "GC content (%)": "40",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "1",
    MM2: "0",
    MM3: "16",
    Efficiency: "61.40",
  },
  {
    Rank: "233",
    "Target sequence": "GTCCCTGTGATGCTCAGCAATGG",
    "Genomic location": "chr8:117835520",
    Strand: "-",
    "GC content (%)": "55",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "18",
    Efficiency: "57.97",
  },
  {
    Rank: "234",
    "Target sequence": "GTCTGTGATGATGTTGTCGTAGG",
    "Genomic location": "chr8:117812917",
    Strand: "+",
    "GC content (%)": "45",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "18",
    Efficiency: "53.85",
  },
  {
    Rank: "235",
    "Target sequence": "TATCCAGACTCAGGACAAAGAGG",
    "Genomic location": "chr8:118110569",
    Strand: "+",
    "GC content (%)": "45",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "3",
    MM3: "14",
    Efficiency: "64.46",
  },
  {
    Rank: "236",
    "Target sequence": "TAGAAACATCAAAGTTGGGTCGG",
    "Genomic location": "chr8:118110347",
    Strand: "+",
    "GC content (%)": "35",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "17",
    Efficiency: "59.44",
  },
  {
    Rank: "237",
    "Target sequence": "CTACACCTCGGACCCCAGCCAGG",
    "Genomic location": "chr8:118110596",
    Strand: "-",
    "GC content (%)": "70",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "17",
    Efficiency: "50.58",
  },
  {
    Rank: "238",
    "Target sequence": "TTGGCTTGTGTTCTGCCTGCAGG",
    "Genomic location": "chr8:117807377",
    Strand: "-",
    "GC content (%)": "55",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "17",
    Efficiency: "42.63",
  },
  {
    Rank: "239",
    "Target sequence": "TTCTTCTGGGTCACTTTGATTGG",
    "Genomic location": "chr8:117804750",
    Strand: "+",
    "GC content (%)": "40",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "17",
    Efficiency: "30.42",
  },
  {
    Rank: "240",
    "Target sequence": "CTGGCAGGTAATGGGAGTATAGG",
    "Genomic location": "chr8:117804859",
    Strand: "+",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "19",
    Efficiency: "56.49",
  },
  {
    Rank: "241",
    "Target sequence": "AAGAGGTACCTGACAGGGATAGG",
    "Genomic location": "chr8:118110220",
    Strand: "-",
    "GC content (%)": "50",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "19",
    Efficiency: "53.05",
  },
  {
    Rank: "242",
    "Target sequence": "TCCTTCTCCCTAGACTTCTCGGG",
    "Genomic location": "chr8:117799888",
    Strand: "-",
    "GC content (%)": "50",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "19",
    Efficiency: "41.87",
  },
  {
    Rank: "243",
    "Target sequence": "AAGGATCATCCCAGGACAGGAGG",
    "Genomic location": "chr8:118110310",
    Strand: "-",
    "GC content (%)": "55",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "3",
    MM3: "15",
    Efficiency: "61.17",
  },
  {
    Rank: "244",
    "Target sequence": "CAAAGACTGGCAAAAGCACAAGG",
    "Genomic location": "chr8:118110122",
    Strand: "-",
    "GC content (%)": "45",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "18",
    Efficiency: "61.12",
  },
  {
    Rank: "245",
    "Target sequence": "TGGGATGATCCTTAGAAAAGAGG",
    "Genomic location": "chr8:118110320",
    Strand: "+",
    "GC content (%)": "40",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "18",
    Efficiency: "58.05",
  },
  {
    Rank: "246",
    "Target sequence": "CAGGGATAGGATCAGACACCAGG",
    "Genomic location": "chr8:118110207",
    Strand: "-",
    "GC content (%)": "55",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "18",
    Efficiency: "55.55",
  },
  {
    Rank: "247",
    "Target sequence": "GGGATGATCCTTAGAAAAGAGGG",
    "Genomic location": "chr8:118110321",
    Strand: "+",
    "GC content (%)": "40",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "18",
    Efficiency: "50.38",
  },
  {
    Rank: "248",
    "Target sequence": "TGTGGCAGAGCTTCCCTGAGAGG",
    "Genomic location": "chr8:117807336",
    Strand: "-",
    "GC content (%)": "60",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "1",
    MM2: "2",
    MM3: "15",
    Efficiency: "63.68",
  },
  {
    Rank: "249",
    "Target sequence": "ATTTTGTCACAGCAGACACCAGG",
    "Genomic location": "chr8:117804778",
    Strand: "+",
    "GC content (%)": "45",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "20",
    Efficiency: "58.12",
  },
  {
    Rank: "250",
    "Target sequence": "GCCAACTCCAGCATCTACAAAGG",
    "Genomic location": "chr8:118110763",
    Strand: "-",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "20",
    Efficiency: "54.90",
  },
  {
    Rank: "251",
    "Target sequence": "AGTACTGTGCCCAGGTGAGCGGG",
    "Genomic location": "chr8:117819667",
    Strand: "-",
    "GC content (%)": "60",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "20",
    Efficiency: "50.81",
  },
  {
    Rank: "252",
    "Target sequence": "CTCCTCACCACCTGCAAGCATGG",
    "Genomic location": "chr8:118110145",
    Strand: "-",
    "GC content (%)": "60",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "17",
    Efficiency: "48.09",
  },
  {
    Rank: "253",
    "Target sequence": "GGGAATAGAAACATCAAAGTTGG",
    "Genomic location": "chr8:118110342",
    Strand: "+",
    "GC content (%)": "35",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "17",
    Efficiency: "45.02",
  },
  {
    Rank: "254",
    "Target sequence": "TGGCTTTGGCCAGCATCGCCTGG",
    "Genomic location": "chr8:118110389",
    Strand: "+",
    "GC content (%)": "65",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "17",
    Efficiency: "42.65",
  },
  {
    Rank: "255",
    "Target sequence": "TGTGTCCTGCCTGGGTCAAGAGG",
    "Genomic location": "chr8:118111046",
    Strand: "+",
    "GC content (%)": "60",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "19",
    Efficiency: "58.53",
  },
  {
    Rank: "256",
    "Target sequence": "GCTGAGCATCACAGGGACGCAGG",
    "Genomic location": "chr8:117835525",
    Strand: "+",
    "GC content (%)": "65",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "19",
    Efficiency: "58.34",
  },
  {
    Rank: "257",
    "Target sequence": "TTAATATGGAACAAACATCCTGG",
    "Genomic location": "chr8:117822533",
    Strand: "-",
    "GC content (%)": "30",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "19",
    Efficiency: "56.96",
  },
  {
    Rank: "258",
    "Target sequence": "ACGACAGGCACAGCAGTGGCAGG",
    "Genomic location": "chr8:117818457",
    Strand: "+",
    "GC content (%)": "65",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "3",
    MM3: "16",
    Efficiency: "49.48",
  },
  {
    Rank: "259",
    "Target sequence": "GCACGCCTGGCTGGGGTCCGAGG",
    "Genomic location": "chr8:118110591",
    Strand: "+",
    "GC content (%)": "80",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "3",
    MM3: "16",
    Efficiency: "43.08",
  },
  {
    Rank: "260",
    "Target sequence": "CAGATTCCTGGAGGCTTTGCAGG",
    "Genomic location": "chr8:117837107",
    Strand: "-",
    "GC content (%)": "55",
    "Self-complementarity": "3",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "19",
    Efficiency: "23.14",
  },
  {
    Rank: "261",
    "Target sequence": "AGTATGAGAAGTAAGTGTCTGGG",
    "Genomic location": "chr8:118110072",
    Strand: "-",
    "GC content (%)": "35",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "21",
    Efficiency: "66.82",
  },
  {
    Rank: "262",
    "Target sequence": "AAGTTACCAAAACATTCTAGCGG",
    "Genomic location": "chr8:118110638",
    Strand: "-",
    "GC content (%)": "30",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "1",
    MM2: "2",
    MM3: "16",
    Efficiency: "64.02",
  },
  {
    Rank: "263",
    "Target sequence": "CCTTAGAGTTATCCCAGAAGTGG",
    "Genomic location": "chr8:117807290",
    Strand: "+",
    "GC content (%)": "45",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "21",
    Efficiency: "56.35",
  },
  {
    Rank: "264",
    "Target sequence": "GCCTACTTCTACTTCCTCCCAGG",
    "Genomic location": "chr8:117812961",
    Strand: "-",
    "GC content (%)": "55",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "18",
    Efficiency: "51.46",
  },
  {
    Rank: "265",
    "Target sequence": "TGCTGGTATTCAAGGGGAAGAGG",
    "Genomic location": "chr8:118110237",
    Strand: "-",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "4",
    MM3: "15",
    Efficiency: "51.12",
  },
  {
    Rank: "266",
    "Target sequence": "TAGGTAAGTGAATTTCCTCCAGG",
    "Genomic location": "chr8:117822445",
    Strand: "-",
    "GC content (%)": "40",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "21",
    Efficiency: "43.37",
  },
  {
    Rank: "267",
    "Target sequence": "GGGCATCGAGGAGCCACAGCCGG",
    "Genomic location": "chr8:118110939",
    Strand: "-",
    "GC content (%)": "70",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "20",
    Efficiency: "53.98",
  },
  {
    Rank: "268",
    "Target sequence": "TGACTGCAGTGAATTTGGAGGGG",
    "Genomic location": "chr8:117819762",
    Strand: "+",
    "GC content (%)": "45",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "19",
    Efficiency: "66.49",
  },
  {
    Rank: "269",
    "Target sequence": "CAAGTGGAGACTCTGCACTTTGG",
    "Genomic location": "chr8:118110498",
    Strand: "+",
    "GC content (%)": "50",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "22",
    Efficiency: "59.80",
  },
  {
    Rank: "270",
    "Target sequence": "AGCAGCTCCTGTCAACACCATGG",
    "Genomic location": "chr8:117807228",
    Strand: "+",
    "GC content (%)": "55",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "21",
    Efficiency: "66.82",
  },
  {
    Rank: "271",
    "Target sequence": "CAGTACTGTGCCCAGGTGAGCGG",
    "Genomic location": "chr8:117819668",
    Strand: "-",
    "GC content (%)": "60",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "21",
    Efficiency: "55.79",
  },
  {
    Rank: "272",
    "Target sequence": "CAATTAATCACTTCAGAGAATGG",
    "Genomic location": "chr8:117835487",
    Strand: "+",
    "GC content (%)": "30",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "3",
    MM3: "18",
    Efficiency: "45.61",
  },
  {
    Rank: "273",
    "Target sequence": "AGCCGGAGAGAAGAACACAGCGG",
    "Genomic location": "chr8:118110922",
    Strand: "-",
    "GC content (%)": "55",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "20",
    Efficiency: "79.02",
  },
  {
    Rank: "274",
    "Target sequence": "GTGTCTGCTGTCTAAGTGCTAGG",
    "Genomic location": "chr8:117830289",
    Strand: "+",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "20",
    Efficiency: "56.22",
  },
  {
    Rank: "275",
    "Target sequence": "GTGCCTCTTTGTCCTGAGTCTGG",
    "Genomic location": "chr8:118110572",
    Strand: "-",
    "GC content (%)": "55",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "22",
    Efficiency: "48.06",
  },
  {
    Rank: "276",
    "Target sequence": "CTCTTTCTAGGTATGATTATCGG",
    "Genomic location": "chr8:117837189",
    Strand: "-",
    "GC content (%)": "30",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "3",
    MM3: "19",
    Efficiency: "19.88",
  },
  {
    Rank: "277",
    "Target sequence": "TCTTCCTCAAAATAGAGACCTGG",
    "Genomic location": "chr8:117799738",
    Strand: "+",
    "GC content (%)": "40",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "21",
    Efficiency: "56.02",
  },
  {
    Rank: "278",
    "Target sequence": "CTGGGCACAGTACTGGGACTTGG",
    "Genomic location": "chr8:117819676",
    Strand: "+",
    "GC content (%)": "60",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "24",
    Efficiency: "45.32",
  },
  {
    Rank: "279",
    "Target sequence": "AGCCTCCGAAATAAAACAAAAGG",
    "Genomic location": "chr8:118110971",
    Strand: "+",
    "GC content (%)": "35",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "24",
    Efficiency: "42.00",
  },
  {
    Rank: "280",
    "Target sequence": "AGGATCATCCCAGGACAGGAGGG",
    "Genomic location": "chr8:118110309",
    Strand: "-",
    "GC content (%)": "55",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "23",
    Efficiency: "61.51",
  },
  {
    Rank: "281",
    "Target sequence": "GGAGAGAAGAACACAGCGGTAGG",
    "Genomic location": "chr8:118110918",
    Strand: "-",
    "GC content (%)": "55",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "23",
    Efficiency: "56.12",
  },
  {
    Rank: "282",
    "Target sequence": "TCAGGCTGGCTGGCAGGTAATGG",
    "Genomic location": "chr8:117804850",
    Strand: "+",
    "GC content (%)": "60",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "23",
    Efficiency: "36.49",
  },
  {
    Rank: "283",
    "Target sequence": "GTTCCTCGTGGTCGCAGGCTTGG",
    "Genomic location": "chr8:117837136",
    Strand: "-",
    "GC content (%)": "65",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "23",
    Efficiency: "27.38",
  },
  {
    Rank: "284",
    "Target sequence": "CAAGTCCCAGTACTGTGCCCAGG",
    "Genomic location": "chr8:117819675",
    Strand: "-",
    "GC content (%)": "60",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "25",
    Efficiency: "55.87",
  },
  {
    Rank: "285",
    "Target sequence": "TGCCATGCTTGCAGGTGGTGAGG",
    "Genomic location": "chr8:118110143",
    Strand: "+",
    "GC content (%)": "60",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "22",
    Efficiency: "55.25",
  },
  {
    Rank: "286",
    "Target sequence": "ATCCCAGAAGTGGCTGCGCGCGG",
    "Genomic location": "chr8:117807300",
    Strand: "+",
    "GC content (%)": "65",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "22",
    Efficiency: "53.37",
  },
  {
    Rank: "287",
    "Target sequence": "ATTGTTATTACAGGTAAGGAAGG",
    "Genomic location": "chr8:117835434",
    Strand: "-",
    "GC content (%)": "30",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "25",
    Efficiency: "51.14",
  },
  {
    Rank: "288",
    "Target sequence": "GGACATTCTCATGAACTTCCTGG",
    "Genomic location": "chr8:117804796",
    Strand: "-",
    "GC content (%)": "45",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "25",
    Efficiency: "44.62",
  },
  {
    Rank: "289",
    "Target sequence": "CTCCTTCTCCCTAGACTTCTCGG",
    "Genomic location": "chr8:117799889",
    Strand: "-",
    "GC content (%)": "50",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "4",
    MM3: "19",
    Efficiency: "22.54",
  },
  {
    Rank: "290",
    "Target sequence": "GTACTTCCTGAGAGGAGGGATGG",
    "Genomic location": "chr8:118110261",
    Strand: "+",
    "GC content (%)": "55",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "5",
    MM3: "18",
    Efficiency: "59.38",
  },
  {
    Rank: "291",
    "Target sequence": "TGTTATTACAGGTAAGGAAGGGG",
    "Genomic location": "chr8:117835432",
    Strand: "-",
    "GC content (%)": "35",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "24",
    Efficiency: "55.67",
  },
  {
    Rank: "292",
    "Target sequence": "TCTCCTTATACTGCTTCTTCTGG",
    "Genomic location": "chr8:117804736",
    Strand: "+",
    "GC content (%)": "40",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "24",
    Efficiency: "13.76",
  },
  {
    Rank: "293",
    "Target sequence": "TCAACACCATCCCTCCTCTCAGG",
    "Genomic location": "chr8:118110267",
    Strand: "-",
    "GC content (%)": "55",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "26",
    Efficiency: "47.74",
  },
  {
    Rank: "294",
    "Target sequence": "TTGTTATTACAGGTAAGGAAGGG",
    "Genomic location": "chr8:117835433",
    Strand: "-",
    "GC content (%)": "30",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "25",
    Efficiency: "52.83",
  },
  {
    Rank: "295",
    "Target sequence": "TTCTATTCCCCTCTTTTCTAAGG",
    "Genomic location": "chr8:118110329",
    Strand: "-",
    "GC content (%)": "35",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "25",
    Efficiency: "34.02",
  },
  {
    Rank: "296",
    "Target sequence": "AGTGGTCAGGGTCAGCCCAACGG",
    "Genomic location": "chr8:117799861",
    Strand: "+",
    "GC content (%)": "60",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "24",
    Efficiency: "60.67",
  },
  {
    Rank: "297",
    "Target sequence": "ACGAGGAACCAGACAGAAAGTGG",
    "Genomic location": "chr8:117837150",
    Strand: "+",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "27",
    Efficiency: "56.13",
  },
  {
    Rank: "298",
    "Target sequence": "GACAAGAGCCAGCTGAGAGCAGG",
    "Genomic location": "chr8:118110998",
    Strand: "+",
    "GC content (%)": "60",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "24",
    Efficiency: "48.63",
  },
  {
    Rank: "299",
    "Target sequence": "CAAAGCCTCCAGGAATCTGAAGG",
    "Genomic location": "chr8:117837111",
    Strand: "+",
    "GC content (%)": "50",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "25",
    Efficiency: "55.75",
  },
  {
    Rank: "300",
    "Target sequence": "CTTCTTGCCTTTGTAGATGCTGG",
    "Genomic location": "chr8:118110756",
    Strand: "+",
    "GC content (%)": "45",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "28",
    Efficiency: "36.18",
  },
  {
    Rank: "301",
    "Target sequence": "AGGGGAAGAGGTACCTGACAGGG",
    "Genomic location": "chr8:118110225",
    Strand: "-",
    "GC content (%)": "55",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "27",
    Efficiency: "65.34",
  },
  {
    Rank: "302",
    "Target sequence": "GCAGTATAAGGAGACAATGATGG",
    "Genomic location": "chr8:117804727",
    Strand: "-",
    "GC content (%)": "40",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "3",
    MM3: "24",
    Efficiency: "50.23",
  },
  {
    Rank: "303",
    "Target sequence": "CAGGCTGGCTGGCAGGTAATGGG",
    "Genomic location": "chr8:117804851",
    Strand: "+",
    "GC content (%)": "60",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "4",
    MM3: "23",
    Efficiency: "34.99",
  },
  {
    Rank: "304",
    "Target sequence": "CTCCTTATACTGCTTCTTCTGGG",
    "Genomic location": "chr8:117804737",
    Strand: "+",
    "GC content (%)": "40",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "29",
    Efficiency: "24.64",
  },
  {
    Rank: "305",
    "Target sequence": "TGGCCTGCATGTGTCCTGCCTGG",
    "Genomic location": "chr8:118111037",
    Strand: "+",
    "GC content (%)": "65",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "3",
    MM3: "25",
    Efficiency: "29.08",
  },
  {
    Rank: "306",
    "Target sequence": "ACTGCAGTGAATTTGGAGGGGGG",
    "Genomic location": "chr8:117819764",
    Strand: "+",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "27",
    Efficiency: "62.43",
  },
  {
    Rank: "307",
    "Target sequence": "GACTGCAGTGAATTTGGAGGGGG",
    "Genomic location": "chr8:117819763",
    Strand: "+",
    "GC content (%)": "50",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "30",
    Efficiency: "51.96",
  },
  {
    Rank: "308",
    "Target sequence": "GCTTTAAACCTGAAATAAAAAGG",
    "Genomic location": "chr8:117819786",
    Strand: "+",
    "GC content (%)": "25",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "4",
    MM3: "24",
    Efficiency: "29.89",
  },
  {
    Rank: "309",
    "Target sequence": "TTCACCCTTTGCAAGAAAAACGG",
    "Genomic location": "chr8:118110709",
    Strand: "-",
    "GC content (%)": "35",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "1",
    MM2: "1",
    MM3: "27",
    Efficiency: "38.43",
  },
  {
    Rank: "310",
    "Target sequence": "GCTCAGCCTTGACGAGGACACGG",
    "Genomic location": "chr8:117812889",
    Strand: "-",
    "GC content (%)": "60",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "31",
    Efficiency: "67.17",
  },
  {
    Rank: "311",
    "Target sequence": "ATCATACCTAGAAAGAGAAGAGG",
    "Genomic location": "chr8:117837195",
    Strand: "+",
    "GC content (%)": "35",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "28",
    Efficiency: "58.54",
  },
  {
    Rank: "312",
    "Target sequence": "GCTTGTGTTCTGCCTGCAGGTGG",
    "Genomic location": "chr8:117807374",
    Strand: "-",
    "GC content (%)": "60",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "30",
    Efficiency: "50.93",
  },
  {
    Rank: "313",
    "Target sequence": "GACCCAGGCAGGACACATGCAGG",
    "Genomic location": "chr8:118111040",
    Strand: "-",
    "GC content (%)": "65",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "3",
    MM3: "28",
    Efficiency: "54.35",
  },
  {
    Rank: "314",
    "Target sequence": "CAAAGAGGCACGCCTGGCTGGGG",
    "Genomic location": "chr8:118110584",
    Strand: "+",
    "GC content (%)": "65",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "3",
    MM3: "29",
    Efficiency: "52.18",
  },
  {
    Rank: "315",
    "Target sequence": "CTCTTACCTGCAAAGCCTCCAGG",
    "Genomic location": "chr8:117837101",
    Strand: "+",
    "GC content (%)": "55",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "31",
    Efficiency: "49.14",
  },
  {
    Rank: "316",
    "Target sequence": "ACCTGGGAGGAAGTAGAAGTAGG",
    "Genomic location": "chr8:117812960",
    Strand: "+",
    "GC content (%)": "50",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "32",
    Efficiency: "63.07",
  },
  {
    Rank: "317",
    "Target sequence": "GGAATAGAAACATCAAAGTTGGG",
    "Genomic location": "chr8:118110343",
    Strand: "+",
    "GC content (%)": "30",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "4",
    MM3: "30",
    Efficiency: "48.72",
  },
  {
    Rank: "318",
    "Target sequence": "CTGGAGGCTTTGCAGGTAAGAGG",
    "Genomic location": "chr8:117837100",
    Strand: "-",
    "GC content (%)": "55",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "36",
    Efficiency: "51.59",
  },
  {
    Rank: "319",
    "Target sequence": "GCCTCCGAAATAAAACAAAAGGG",
    "Genomic location": "chr8:118110972",
    Strand: "+",
    "GC content (%)": "35",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "35",
    Efficiency: "50.96",
  },
  {
    Rank: "320",
    "Target sequence": "GGCCTGCATGTGTCCTGCCTGGG",
    "Genomic location": "chr8:118111038",
    Strand: "+",
    "GC content (%)": "65",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "4",
    MM3: "32",
    Efficiency: "41.91",
  },
  {
    Rank: "321",
    "Target sequence": "GCACAGCAGTGGCAGGCCAGCGG",
    "Genomic location": "chr8:117818464",
    Strand: "+",
    "GC content (%)": "70",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "38",
    Efficiency: "64.02",
  },
  {
    Rank: "322",
    "Target sequence": "TGTTCTTCAGGCTGGCTGGCAGG",
    "Genomic location": "chr8:117804844",
    Strand: "+",
    "GC content (%)": "60",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "6",
    MM3: "33",
    Efficiency: "47.82",
  },
  {
    Rank: "323",
    "Target sequence": "CTGGCTGGGACTGAGAGACCAGG",
    "Genomic location": "chr8:117819723",
    Strand: "+",
    "GC content (%)": "65",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "0",
    MM3: "42",
    Efficiency: "46.77",
  },
  {
    Rank: "324",
    "Target sequence": "TAGAATGTTTTGGTAACTTTCGG",
    "Genomic location": "chr8:118110642",
    Strand: "+",
    "GC content (%)": "25",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "1",
    MM2: "3",
    MM3: "37",
    Efficiency: "36.92",
  },
  {
    Rank: "325",
    "Target sequence": "TCTACTCTCCTTTTTATTTCAGG",
    "Genomic location": "chr8:117819794",
    Strand: "-",
    "GC content (%)": "30",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "7",
    MM3: "39",
    Efficiency: "11.81",
  },
  {
    Rank: "326",
    "Target sequence": "ATTTTCTCCCCTTTTTGCTGTGG",
    "Genomic location": "chr8:118110667",
    Strand: "+",
    "GC content (%)": "40",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "3",
    MM3: "48",
    Efficiency: "48.25",
  },
  {
    Rank: "327",
    "Target sequence": "CAGGCAGCCTGAGCAAAAAAGGG",
    "Genomic location": "chr8:117835544",
    Strand: "+",
    "GC content (%)": "50",
    "Self-complementarity": "4",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "51",
    Efficiency: "37.85",
  },
  {
    Rank: "328",
    "Target sequence": "AGGCAGCCTGAGCAAAAAAGGGG",
    "Genomic location": "chr8:117835545",
    Strand: "+",
    "GC content (%)": "50",
    "Self-complementarity": "3",
    MM0: "0",
    MM1: "0",
    MM2: "4",
    MM3: "47",
    Efficiency: "62.23",
  },
  {
    Rank: "329",
    "Target sequence": "GCCAGCCAGCCTGAAGAACATGG",
    "Genomic location": "chr8:117804841",
    Strand: "-",
    "GC content (%)": "60",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "51",
    Efficiency: "59.23",
  },
  {
    Rank: "330",
    "Target sequence": "TGGCTGGGACTGAGAGACCAGGG",
    "Genomic location": "chr8:117819724",
    Strand: "+",
    "GC content (%)": "60",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "2",
    MM3: "51",
    Efficiency: "57.68",
  },
  {
    Rank: "331",
    "Target sequence": "TACAGGTAAGGAAGGGGCTGTGG",
    "Genomic location": "chr8:117835426",
    Strand: "-",
    "GC content (%)": "55",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "3",
    MM3: "50",
    Efficiency: "48.12",
  },
  {
    Rank: "332",
    "Target sequence": "GCTGGGACTGAGAGACCAGGGGG",
    "Genomic location": "chr8:117819726",
    Strand: "+",
    "GC content (%)": "65",
    "Self-complementarity": "3",
    MM0: "0",
    MM1: "0",
    MM2: "6",
    MM3: "49",
    Efficiency: "63.81",
  },
  {
    Rank: "333",
    "Target sequence": "ATATCTGTAAAAATCAAAGATGG",
    "Genomic location": "chr8:117804890",
    Strand: "+",
    "GC content (%)": "20",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "5",
    MM3: "54",
    Efficiency: "48.59",
  },
  {
    Rank: "334",
    "Target sequence": "TATCTGTAAAAATCAAAGATGGG",
    "Genomic location": "chr8:117804891",
    Strand: "+",
    "GC content (%)": "20",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "4",
    MM3: "56",
    Efficiency: "53.26",
  },
  {
    Rank: "335",
    "Target sequence": "CTCGCCCTTTTGTTTTATTTCGG",
    "Genomic location": "chr8:118110976",
    Strand: "-",
    "GC content (%)": "35",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "3",
    MM3: "58",
    Efficiency: "27.71",
  },
  {
    Rank: "336",
    "Target sequence": "TTTTCTCCCCTTTTTGCTGTGGG",
    "Genomic location": "chr8:118110668",
    Strand: "+",
    "GC content (%)": "40",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "3",
    MM3: "59",
    Efficiency: "44.95",
  },
  {
    Rank: "337",
    "Target sequence": "CTGGGACTGAGAGACCAGGGGGG",
    "Genomic location": "chr8:117819727",
    Strand: "+",
    "GC content (%)": "65",
    "Self-complementarity": "3",
    MM0: "0",
    MM1: "0",
    MM2: "4",
    MM3: "58",
    Efficiency: "75.30",
  },
  {
    Rank: "338",
    "Target sequence": "ATCCCAGGACAGGAGGGGAGAGG",
    "Genomic location": "chr8:118110303",
    Strand: "-",
    "GC content (%)": "65",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "4",
    MM3: "59",
    Efficiency: "48.48",
  },
  {
    Rank: "339",
    "Target sequence": "AGCCAGCCTGAAGAACATGGTGG",
    "Genomic location": "chr8:117804838",
    Strand: "-",
    "GC content (%)": "55",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "3",
    MM3: "68",
    Efficiency: "73.47",
  },
  {
    Rank: "340",
    "Target sequence": "TGTCTAAAGTATCCAGACTCAGG",
    "Genomic location": "chr8:118110560",
    Strand: "+",
    "GC content (%)": "40",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "1",
    MM3: "74",
    Efficiency: "55.75",
  },
  {
    Rank: "341",
    "Target sequence": "GGCTGGGACTGAGAGACCAGGGG",
    "Genomic location": "chr8:117819725",
    Strand: "+",
    "GC content (%)": "65",
    "Self-complementarity": "3",
    MM0: "0",
    MM1: "1",
    MM2: "9",
    MM3: "61",
    Efficiency: "62.56",
  },
  {
    Rank: "342",
    "Target sequence": "GCTTTGCAGGTAAGAGGCCCTGG",
    "Genomic location": "chr8:117837094",
    Strand: "-",
    "GC content (%)": "60",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "10",
    MM3: "76",
    Efficiency: "44.41",
  },
  {
    Rank: "343",
    "Target sequence": "TCCCAGGACAGGAGGGGAGAGGG",
    "Genomic location": "chr8:118110302",
    Strand: "-",
    "GC content (%)": "65",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "3",
    MM3: "88",
    Efficiency: "52.52",
  },
  {
    Rank: "344",
    "Target sequence": "CCCCCTCTCCCCTCCTGTCCTGG",
    "Genomic location": "chr8:118110300",
    Strand: "+",
    "GC content (%)": "75",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "9",
    MM3: "85",
    Efficiency: "30.55",
  },
  {
    Rank: "345",
    "Target sequence": "GCAGGCAGCCTGAGCAAAAAAGG",
    "Genomic location": "chr8:117835543",
    Strand: "+",
    "GC content (%)": "55",
    "Self-complementarity": "4",
    MM0: "0",
    MM1: "0",
    MM2: "15",
    MM3: "78",
    Efficiency: "30.32",
  },
  {
    Rank: "346",
    "Target sequence": "ACCATGTTCTTCAGGCTGGCTGG",
    "Genomic location": "chr8:117804840",
    Strand: "+",
    "GC content (%)": "55",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "10",
    MM3: "104",
    Efficiency: "44.86",
  },
  {
    Rank: "347",
    "Target sequence": "CCCCTCTCCCCTCCTGTCCTGGG",
    "Genomic location": "chr8:118110301",
    Strand: "+",
    "GC content (%)": "70",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "22",
    MM3: "92",
    Efficiency: "40.33",
  },
  {
    Rank: "348",
    "Target sequence": "TTTACTCCTCTTCTCTTTCTAGG",
    "Genomic location": "chr8:117837201",
    Strand: "-",
    "GC content (%)": "35",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "18",
    MM3: "116",
    Efficiency: "18.08",
  },
  {
    Rank: "349",
    "Target sequence": "TTTTATTTTCTAGATTATTCAGG",
    "Genomic location": "chr8:117822588",
    Strand: "-",
    "GC content (%)": "15",
    "Self-complementarity": "1",
    MM0: "0",
    MM1: "0",
    MM2: "5",
    MM3: "144",
    Efficiency: "33.85",
  },
  {
    Rank: "350",
    "Target sequence": "TAGAGACCTGGTCTTTAAAGAGG",
    "Genomic location": "chr8:117799750",
    Strand: "+",
    "GC content (%)": "40",
    "Self-complementarity": "2",
    MM0: "0",
    MM1: "0",
    MM2: "11",
    MM3: "144",
    Efficiency: "48.46",
  },
  {
    Rank: "351",
    "Target sequence": "GTCCACCATGTTCTTCAGGCTGG",
    "Genomic location": "chr8:117804836",
    Strand: "+",
    "GC content (%)": "55",
    "Self-complementarity": "0",
    MM0: "0",
    MM1: "0",
    MM2: "12",
    MM3: ">=305",
    Efficiency: "42.39",
  },
];
export const Table = () => {
  return (
    <div className="px-4 sm:px-6 lg:px-8">
      <div className="sm:flex sm:items-center">
        <div className="sm:flex-auto">
          <h1 className="text-xl font-semibold text-gray-900">Results</h1>
          <p className="mt-2 text-sm text-gray-700">
            A list of all the users in your account including their name, title,
            email and role.
          </p>
        </div>
      </div>
      <div className="mt-8 flex flex-col">
        <div className="-my-2 -mx-4 sm:-mx-6 lg:-mx-8">
          <div className="inline-block min-w-full py-2 align-middle">
            <div className="shadow-sm ring-1 ring-black ring-opacity-5">
              <table
                className="min-w-full border-separate"
                style={{ borderSpacing: 0 }}
              >
                <thead className="bg-gray-50">
                  <tr>
                    {columns.map((column) => (
                      <th
                        key={column.valueOf()}
                        scope="col"
                        className="sticky top-0 z-10 border-b border-gray-300 bg-gray-50 bg-opacity-75 py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 backdrop-blur backdrop-filter sm:pl-6 lg:pl-8"
                      >
                        {column.valueOf()}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody className="bg-white">
                  {data.map((datum, datumIdx) => (
                    <tr key={`row-${datumIdx}`}>
                      {columns.map((column) => {
                        const key = column.valueOf() as keyof typeof datum;
                        return (
                          <td
                            key={`row-${datumIdx}-${key}`}
                            className="border-b border-gray-200 py-3.5 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6 lg:pl-8"
                          >
                            {datum[key]}
                          </td>
                        );
                      })}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
